pipeline {
    agent { label 'builder' }

    stages {
    
        stage('Build') {
        
            steps {
            sleep 60
           bat 'echo "Hello world!"'
           sleep 60
            }
        }
  }
}   
