pipeline {
    agent { label 'builder' }
     options {
     lock(quantity: 2, resource: 'builder2')
   
   }
   
    stages {
        stage('Build') {
            steps {
            sleep 60
                sh 'echo "Hello world!"'
            sleep 60
           }
        }
    }
}
