pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                build job: "blockerbuild", propagate: true, wait: true
                bat 'echo "Hello world!"'
            }
        }
    }
}   
